logging:
  level:
    root: INFO
    me.binhnguyen: INFO

server:
  port: 7080

spring:
  datasource:
    server:
      host: localhost
      port: 5432
    url: jdbc:postgresql://${spring.datasource.server.host}:${spring.datasource.server.port}/seraphinadb
    username: seraphina
    password: seraphina@123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ansi:
    enabled: DETECT