# stage 1: install dependencies
FROM python:3.12-slim as builder

WORKDIR /zalo

USER root

RUN apt-get update && apt-get install -y \
  build-essential \
  libpq-dev \
  && rm -rf /var/lib/apt/lists/*

COPY requirements.txt requirements.txt

RUN pip install --upgrade pip
RUN pip install --upgrade pip setuptools wheel
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt

# stage 2: run
FROM python:3.12-slim

WORKDIR /zalo

USER root

COPY --from=builder /zalo /zalo
COPY --from=builder /install /usr/local
COPY src src

CMD ["python", "src/Application.py"]